# Generated by Django 3.2.25 on 2024-10-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor_device_list',
            name='job_frequency',
        ),
        migrations.RemoveField(
            model_name='monitor_device_list',
            name='job_start_time',
        ),
    ]
