# Generated by Django 3.2.25 on 2024-10-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderweb', '0002_alter_monitor_device_list_job_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_type',
            name='job_frequency',
            field=models.CharField(default=5, max_length=10),
            preserve_default=False,
        ),
    ]
