# Generated by Django 3.2.25 on 2024-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderweb', '0003_check_log_notice_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_device_list',
            name='attr1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='monitor_device_list',
            name='attr2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='monitor_device_list',
            name='attr3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='monitor_device_list',
            name='attr4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='monitor_device_list',
            name='attr5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
