# Generated by Django 3.2.25 on 2024-12-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderweb', '0007_monitor_status_ref_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_device_list',
            name='stop_before',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
