# Generated by Django 3.2.25 on 2025-01-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderweb', '0008_monitor_device_list_stop_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_device_list',
            name='stop_before',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
