# Generated by Django 3.2.25 on 2024-06-14 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('mach_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mach_name', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mach_update_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process_Type',
            fields=[
                ('process_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('process_name', models.CharField(max_length=50)),
                ('process_tw', models.CharField(max_length=50)),
                ('process_cn', models.CharField(max_length=50)),
                ('process_vn', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_type_update_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plant_update_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField()),
                ('plant', models.CharField(max_length=50)),
                ('mach_no', models.CharField(max_length=50)),
                ('process_type', models.CharField(max_length=50)),
                ('data_time', models.CharField(max_length=50)),
                ('parameter_name', models.CharField(max_length=50)),
                ('parameter_value', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_value_create_at', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_value_update_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterDefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.CharField(max_length=50)),
                ('parameter_name', models.CharField(max_length=50)),
                ('parameter_tw', models.CharField(max_length=50)),
                ('parameter_cn', models.CharField(max_length=50)),
                ('parameter_vn', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_define_create_at', to=settings.AUTH_USER_MODEL)),
                ('mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_mach', to='collection.machine')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_plant', to='collection.plant')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_process_type', to='collection.process_type')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_define_update_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
