# Generated by Django 3.2.25 on 2024-06-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametervalue',
            old_name='mach_no',
            new_name='mach',
        ),
    ]
