# Generated by Django 3.2.25 on 2024-06-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_rename_mach_no_parametervalue_mach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdefine',
            name='data_time',
        ),
    ]
