# Generated by Django 3.2.25 on 2024-06-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20240614_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_prod_info',
            name='remark',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
