# Generated by Django 3.2.25 on 2024-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_daily_prod_info_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_prod_info',
            name='coagulant_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='latex_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_name_a1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_name_a2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_name_b1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_name_b2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_size_a1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_size_a2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_size_b1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='production_size_b2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='tooling_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
