# Generated by Django 3.2.25 on 2024-06-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20240614_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_prod_info',
            name='mach',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='daily_info_mach', to='collection.machine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='mach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_value_mach', to='collection.machine'),
        ),
    ]
