# Generated by Django 3.2.25 on 2024-06-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20240614_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_prod_info',
            old_name='coagulant_time',
            new_name='coagulant_time_hour',
        ),
        migrations.RenameField(
            model_name='daily_prod_info',
            old_name='latex_time',
            new_name='coagulant_time_min',
        ),
        migrations.RenameField(
            model_name='daily_prod_info',
            old_name='tooling_time',
            new_name='latex_time_hour',
        ),
        migrations.AddField(
            model_name='daily_prod_info',
            name='latex_time_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daily_prod_info',
            name='tooling_time_hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='daily_prod_info',
            name='tooling_time_min',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
