# Generated by Django 3.2.25 on 2024-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20240614_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdefine',
            name='show_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process_type',
            name='show_order',
            field=models.IntegerField(default=0),
        ),
    ]
