# Generated by Django 3.2.25 on 2024-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20240615_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdefine',
            name='base_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdefine',
            name='control_range_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdefine',
            name='control_range_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parameterdefine',
            name='sampling_frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameterdefine',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
