# Generated by Django 3.2.25 on 2024-06-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20240617_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='plant',
            field=models.ForeignKey(default='GDNBR', on_delete=django.db.models.deletion.CASCADE, related_name='mach_plant', to='collection.plant'),
            preserve_default=False,
        ),
    ]
