# Generated by Django 3.2.25 on 2024-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_machine_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdefine',
            name='auto_value',
            field=models.BooleanField(default=False),
        ),
    ]
