# Generated by Django 3.2.25 on 2024-07-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20240719_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdefine',
            name='param_type',
        ),
        migrations.DeleteModel(
            name='Parameter_Type',
        ),
    ]
