# Generated by Django 3.2.25 on 2024-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0019_auto_20240719_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdefine',
            name='side',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
