# Generated by Django 3.2.25 on 2024-07-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0023_auto_20240719_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdefine',
            name='param_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='param_param_type', to='collection.parameter_type'),
            preserve_default=False,
        ),
    ]
