# Generated by Django 3.2.25 on 2024-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0024_alter_parameterdefine_param_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_type',
            name='param_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
