# Generated by Django 3.2.25 on 2024-07-23 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0025_parameter_type_param_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_prod_info',
            name='prod_name_a1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='prod_name_a2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='prod_name_b1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='prod_name_b2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Daily_Prod_Info_Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField()),
                ('line', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_info_head_create_at', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
