# Generated by Django 3.2.25 on 2024-07-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0027_auto_20240725_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_prod_info',
            name='remark2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
