# Generated by Django 3.2.25 on 2024-07-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0028_alter_daily_prod_info_remark2'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_prod_info_head',
            name='mach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_info_head_mach', to='collection.machine'),
        ),
        migrations.AddField(
            model_name='daily_prod_info_head',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_info_head_plant', to='collection.plant'),
        ),
    ]
