# Generated by Django 3.2.25 on 2024-07-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0029_auto_20240730_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='mold_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
