# Generated by Django 3.2.25 on 2024-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0032_parameterdefine_input_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameterdefine',
            name='data_owner',
        ),
        migrations.AddField(
            model_name='parameterdefine',
            name='text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
