# Generated by Django 3.2.25 on 2024-08-08 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0033_auto_20240806_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_prod_info',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_info_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='daily_prod_info',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_info_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='daily_prod_info_head',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_info_head_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mach_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parameter_type',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_type_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parameterdefine',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_define_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parameterdefine',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_define_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_value_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_value_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plant',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plant_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process_type',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_type_update_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lab_Parameter_Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=50)),
                ('process_type', models.CharField(max_length=50)),
                ('parameter_name', models.CharField(max_length=50)),
                ('control_range_low', models.FloatField(blank=True, null=True)),
                ('base_line', models.FloatField(blank=True, null=True)),
                ('control_range_high', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lab_param_create_by', to=settings.AUTH_USER_MODEL)),
                ('mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_param_mach', to='collection.machine')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_param_plant', to='collection.plant')),
            ],
        ),
    ]
