# Generated by Django 3.2.25 on 2024-08-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0035_auto_20240808_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdefine',
            name='param_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_param_type', to='collection.parameter_type'),
        ),
    ]
