# Generated by Django 3.2.25 on 2024-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0036_alter_parameterdefine_param_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_type',
            name='control_high_column',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameter_type',
            name='control_low_column',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameter_type',
            name='control_table',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
