# Generated by Django 3.2.25 on 2024-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0037_auto_20240808_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdefine',
            name='param_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
