# Generated by Django 3.2.25 on 2024-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0038_alter_parameterdefine_param_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_type',
            name='control_table',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
