# Generated by Django 3.2.25 on 2024-08-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0039_alter_parameter_type_control_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_type',
            name='control_table',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
