# Generated by Django 3.2.25 on 2025-03-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0041_auto_20241113_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterdefine',
            name='pda_value',
            field=models.BooleanField(default=False),
        ),
    ]
