# Generated by Django 3.2.25 on 2025-03-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0042_parameterdefine_pda_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterdefine',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='parameterdefine',
            name='create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='param_define_create_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
