# Generated by Django 3.2.25 on 2024-07-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_auto_20240716_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageoption',
            name='roles',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
