# Generated by Django 3.2.25 on 2024-07-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_homepageoption_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepageoption',
            old_name='url',
            new_name='url_name',
        ),
    ]
