# Generated by Django 3.2.25 on 2024-07-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_url_homepageoption_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageoption',
            name='name_cn',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageoption',
            name='name_tw',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepageoption',
            name='name_vn',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
