# Generated by Django 3.2.25 on 2024-12-07 08:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.CharField(max_length=100, null=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attr_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('attr_name', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('bin_name', models.CharField(max_length=100)),
                ('pos_x', models.IntegerField(blank=True, null=True)),
                ('pos_y', models.IntegerField(blank=True, null=True)),
                ('bin_w', models.IntegerField(blank=True, null=True)),
                ('bin_l', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.CharField(max_length=100, null=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.CharField(max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.area')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('wh_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('wh_name', models.CharField(max_length=100)),
                ('wh_comment', models.CharField(blank=True, max_length=500, null=True)),
                ('wh_bg', models.ImageField(blank=True, null=True, upload_to='warehouse_images/')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.CharField(blank=True, max_length=50, null=True)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bin_Attr_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.CharField(max_length=100, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.attribute')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.bin')),
            ],
        ),
        migrations.CreateModel(
            name='Area_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_by', models.CharField(max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.area')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
    ]
