# Generated by Django 3.2.25 on 2024-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin_value_history',
            name='act_type',
            field=models.CharField(default='STOCKOUT', max_length=10),
            preserve_default=False,
        ),
    ]
