# Generated by Django 3.2.25 on 2024-12-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_action_qty_bin_value_history_act_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin_value_history',
            name='old_qty',
            field=models.IntegerField(),
        ),
    ]
