# Generated by Django 3.2.25 on 2024-12-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20241226_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
