# Generated by Django 3.2.25 on 2024-12-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinform',
            old_name='comment',
            new_name='desc',
        ),
    ]
