# Generated by Django 3.2.25 on 2024-12-31 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0010_auto_20241228_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unittype_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackMethod',
            fields=[
                ('pack_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packmethod_create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
