# Generated by Django 3.2.25 on 2025-01-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_auto_20250103_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinformdetail',
            old_name='order_no',
            new_name='product_no',
        ),
        migrations.RenameField(
            model_name='stockoutform',
            old_name='order_no',
            new_name='product_no',
        ),
    ]
