# Generated by Django 3.2.25 on 2025-01-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_auto_20250103_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin_value',
            old_name='product_no',
            new_name='product_order',
        ),
        migrations.RenameField(
            model_name='bin_value_history',
            old_name='product_no',
            new_name='product_order',
        ),
        migrations.RenameField(
            model_name='stockinformdetail',
            old_name='product_no',
            new_name='product_order',
        ),
        migrations.RenameField(
            model_name='stockoutform',
            old_name='product_no',
            new_name='product_order',
        ),
    ]
