# Generated by Django 3.2.25 on 2025-01-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_auto_20250103_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin_value_history',
            name='batch_no',
            field=models.CharField(default='STIN202412032', max_length=50),
            preserve_default=False,
        ),
    ]
