# Generated by Django 3.2.25 on 2025-01-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_auto_20250103_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin_value_history',
            old_name='act_qty',
            new_name='minus_qty',
        ),
        migrations.RenameField(
            model_name='bin_value_history',
            old_name='new_qty',
            new_name='plus_qty',
        ),
        migrations.RenameField(
            model_name='bin_value_history',
            old_name='old_qty',
            new_name='remain_qty',
        ),
    ]
