# Generated by Django 3.2.25 on 2025-01-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_auto_20250106_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinformdetail',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockinformdetail',
            name='purchase_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockoutformdetail',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockoutformdetail',
            name='purchase_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
