# Generated by Django 3.2.25 on 2025-01-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_auto_20250118_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin_value',
            name='purchase_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bin_value_history',
            name='purchase_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
