# Generated by Django 3.2.25 on 2025-01-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_auto_20250118_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutformdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockoutformdetail',
            name='form_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockout_detail_form', to='warehouse.stockoutform'),
        ),
    ]
