# Generated by Django 3.2.25 on 2025-01-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_auto_20250118_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='customer_no',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='gift_bin',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='gift_qty',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='lot_no',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='order_bin',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='order_qty',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='packing_type',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='purchase_qty',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='sap_mtr_no',
        ),
        migrations.RemoveField(
            model_name='stockoutformdetail',
            name='supplier',
        ),
    ]
