# Generated by Django 3.2.25 on 2025-01-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_auto_20250118_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutformdetail',
            name='order_bin',
            field=models.ForeignKey(default='B001', on_delete=django.db.models.deletion.DO_NOTHING, related_name='stockout_order_bin', to='warehouse.bin'),
            preserve_default=False,
        ),
    ]
