# Generated by Django 3.2.25 on 2025-02-17 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0025_warehouse_wh_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_plant_create_by', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_plant_update_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
